# Generated by Django 5.0.3 on 2024-03-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
